### ISSUE TITLE
Carthage support + build on travis-ci

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQCoreDataKit#92]
Currently `carthage build --no-skip-current --configuration Release` fails.

I don't care enough about Carthage to fix it, so if someone wants to fix this, please do! 😄

Once it works, add this stage at the end of the `jobs:` entry in the [`.travis.yml` config](https://github.com/jessesquires/JSQCoreDataKit/blob/develop/.travis.yml):

```yaml
    - stage: carthage
      osx_image: xcode11
      name: carthage
      os: osx
      script: carthage build --no-skip-current --configuration Release
```

Then add `- carthage` to the end of `stages:`.
